services:
  app:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: cronnect
      DATABASE_PASSWORD: password
      DATABASE_NAME: cronnect
      DATABASE_PORT: "5432"
      DATABASE_SSLMODE: disable
      DATABASE_TIMEZONE: UTC
      REDIS_ADDR: redis:6379
      WORKER_COUNT: "3"
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: cronnect
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cronnect
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
