version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: cronnect
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cronnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
